baseURL = "https://cloudnativos.es/"
languageCode = "es"
title = "Cloud Native Days Spain 2025"
defaultContentLanguage = "es"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[params]
    title = "#3 Virtual Kubernetes Community Days"
    date = "October 28th and 29th, 2025"
    description = "Forma parte de la primera comunidad de hispanohablantes de Kubernetes. Descubre un evento de tres días en español lleno de experiencias, empresas emergentes y personas a las que les gusta tanto la tecnología como a ti."
    images = ["/images/featured/cloudnativos-featured-02.png"]
    email = " hello@cloudnativos.es"
    keywords = "event, cloudnative, spain, kubernetes, google, cloud"
    copyright = "Organized with ❤️  by Cloud Nativos Spain."
    cfpUrl = "https://sessionize.com/cloudnativos-2025/"
    joinURL = "https://tickets.cloudnativos.es" 
    appleTouchIcon = "/apple-icon.png"
    favicon32 = "/images/logos/favicon-32x32.ico"
    favicon16 = "/images/logos/favicon-16x16.ico"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#0000ff"
    submitCFP = "false"
    joinEvent = "true"

[params.logos]
    jumbo = "/images/logos/cloudnativos-logo-white.png"
    header = "/images/logos/cloudnativos-logo-comp.png"
    footer = "/images/logos/cloudnativos-logo-white.png"

[menu]
[[menu.main]]
    identifier = "tickets"
    name = "Tickets"
    url = "https://tickets.cloudnativos.es/"
    weight = 190
    external = true

[languages]
[languages.en]
    weight = 2
    languageName = "gb"
    languageCode = "en"

[languages.es]
    weight = 1
    languageName = "es"
    languageCode = "es"

[languages.es.params]
    description = "Forma parte de la primera comunidad de hispanohablantes de Kubernetes. Descubre un evento de tres días en español lleno de experiencias, empresas emergentes y personas a las que les gusta tanto"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

